spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jtsys?characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
  thymeleaf: #thymeleaf
    prefix: classpath:/templates/pages/

mybatis:
  mapper-locations:
  - classpath:/mapper/*/*.xml
logging:
  level:
    com.tea: debug
